name: Run PowerShell script
on:
  push:
  pull_request:

jobs:
  run_powershell_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell
  
    - name: Run PowerShell script
      shell: pwsh
      run: |
        # Replace 'path/to/your/script.ps1' with the actual path to your PowerShell script
        ./combineMarkdown.ps1

    - name: Build PDF
      uses: baileyjm02/markdown-to-pdf@v1
      with:
          input_path: ./.github/workflows/bin/
          # Specify images dir
          images_dir: ./.github/workflows/bin/images/
          image_import: images
          # Build HTML version
          build_html: true
          
          # Path to output (this should be the same as the Upload Artifiact path)
          output_dir: ./.github/workflows/bin/
    - name: Upload-Artifact
      uses: actions/upload-artifact@v3
      with:
          name: qlcplus-docs-build
          path: ./.github/workflows/bin/
